kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# 3 control plane node and 1 workers
nodes:
- role: control-plane
# - role: worker
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry:8282"]
    endpoint = ["https://registry:8282"]
  [plugins."io.containerd.grpc.v1.cri".registry.configs."registry:8282".tls]
    insecure_skip_verify = true
