---
# website::tag::1:: Deploy the training/webapp Docker Container: https://hub.docker.com/r/training/webapp/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        # website::tag::2:: The container runs a Python webapp on port 5000 that responds with "Hello, World!"
        - name: hello-world
          image: training/webapp:latest
          ports:
            - containerPort: 5000
---
# website::tag::3:: Expose the Python webapp on port 5000 via a Kubernetes LoadBalancer.
kind: Service
apiVersion: v1
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      targetPort: 5000
      port: 5000
  type: LoadBalancer
